const imgTheme1 = require('../../assets/images/themes/theme_1.png');
const imgTheme3 = require('../../assets/images/themes/3.png');
const imgTheme4 = require('../../assets/images/themes/4.png');
const imgTheme5 = require('../../assets/images/themes/5.png');
const imgTheme6 = require('../../assets/images/themes/6.png');
const imgTheme7 = require('../../assets/images/themes/7.png');
const imgTheme8 = require('../../assets/images/themes/8.png');

export const listTheme = [
  {
    imgLocal: imgTheme1,
    id: 1,
    group_id: null,
    name: 'Theme 1',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-ExtraBold',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 2,
      owner_id: 2,
      type: 'theme',
      name: '2.png',
      url: '/assets/images/themes/bg/2.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme1,
    id: 2,
    group_id: null,
    name: 'Theme 1',
    flag: null,
    is_free: 0,
    font_family: 'Montserrat-ExtraBold',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 2,
      owner_id: 2,
      type: 'theme',
      name: '2.png',
      url: '/assets/images/themes/bg/2.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme3,
    id: 3,
    group_id: null,
    name: 'Theme 2',
    flag: null,
    is_free: 0,
    font_family: 'LucidaGrande',
    font_size: 24,
    line_height: 38,
    text_color: '#000000',
    text_shadow: null,
    text_shadow_offset: null,
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 3,
      owner_id: 3,
      type: 'theme',
      name: '3.png',
      url: '/assets/images/themes/bg/3.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme4,
    id: 4,
    group_id: null,
    name: 'Theme 3',
    flag: null,
    is_free: 0,
    font_family: 'KronaOne-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFF0BB',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 4,
      owner_id: 4,
      type: 'theme',
      name: '4.png',
      url: '/assets/images/themes/bg/4.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme5,
    id: 5,
    group_id: null,
    name: 'Theme 4',
    flag: null,
    is_free: 0,
    font_family: 'Lobster-Regular',
    font_size: 24,
    line_height: 34,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 5,
      owner_id: 5,
      type: 'theme',
      name: '5.png',
      url: '/assets/images/themes/bg/5.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme7,
    id: 7,
    group_id: null,
    name: 'Theme 6',
    flag: null,
    is_free: 0,
    font_family: 'FjallaOne-Regular',
    font_size: 26,
    line_height: 36,
    text_color: '#FFD600',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 7,
      owner_id: 7,
      type: 'theme',
      name: '7.png',
      url: '/assets/images/themes/bg/7.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme6,
    id: 6,
    group_id: null,
    name: 'Theme 5',
    flag: null,
    is_free: 0,
    font_family: 'Anton-Regular',
    font_size: 24,
    line_height: 40,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 6,
      owner_id: 6,
      type: 'theme',
      name: '6.png',
      url: '/assets/images/themes/bg/6.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
  {
    imgLocal: imgTheme8,
    id: 8,
    group_id: null,
    name: 'Theme 7',
    flag: null,
    is_free: 0,
    font_family: 'AbrilFatface-Regular',
    font_size: 26,
    line_height: 42,
    text_color: '#FFFFFF',
    text_shadow: 'rgba(0, 0, 0, 0.75)',
    text_shadow_offset: '{"width":1,"height":1}',
    background_color: null,
    bg_image_color: null,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    background: {
      id: 8,
      owner_id: 8,
      type: 'theme',
      name: '8.png',
      url: '/assets/images/themes/bg/8.png',
      created_at: '2023-03-06T06:29:50.000000Z',
      updated_at: null,
    },
  },
];
