export const listFact = [
  {
    id: 1,
    order: null,
    category_id: 8,
    title:
      'The type of music you listen to affects the way you perceive the world.',
    author: null,
    has_notif: 0,
    count_share: 0,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    like: null,
    repeat: null,
  },
  {
    id: 2,
    order: null,
    category_id: 7,
    title:
      'People who view TV crime shows consistently overestimate the frequency of crime in the world.',
    author: null,
    has_notif: 0,
    count_share: 0,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    like: null,
    repeat: null,
  },
  {
    id: 3,
    order: null,
    category_id: 9,
    title:
      'The two most effective treatments for battling depression are exercise and spending time with pets.',
    author: null,
    has_notif: 0,
    count_share: 0,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    like: null,
    repeat: null,
  },
  {
    id: 4,
    order: null,
    category_id: 9,
    title: 'A chameleon’s tongue is twice the length of its body.',
    author: null,
    has_notif: 0,
    count_share: 0,
    status: 2,
    created_at: '2023-03-06T06:29:50.000000Z',
    updated_at: null,
    like: null,
    repeat: null,
  },
];
