// Abstract themes
const abstract4 = require("../../assets/images/theme/abstract-4.png");
const abstract9 = require("../../assets/images/theme/abstract-9.png");
const abstract10 = require("../../assets/images/theme/abstract-10.png");
const abstract33 = require("../../assets/images/theme/abstract-33.png");
// Cityscape
const cityScape8 = require("../../assets/images/theme/cityscape-8.png");
const cityScape22 = require("../../assets/images/theme/cityscape-22.png");
const cityScape23 = require("../../assets/images/theme/cityscape-23.png");
const cityScape24 = require("../../assets/images/theme/cityscape-24.png");
const cityScape38 = require("../../assets/images/theme/cityscape-38.png");
const cityScape39 = require("../../assets/images/theme/cityscape-39.png");

// Illustration
const illustration2 = require("../../assets/images/theme/illustration-2.png");
const illustration3 = require("../../assets/images/theme/illustration-3.png");
const illustration6 = require("../../assets/images/theme/illustration-6.png");
const illustration20 = require("../../assets/images/theme/illustration-20.png");
const illustration21 = require("../../assets/images/theme/illustration-21.png");
const illustration37 = require("../../assets/images/theme/illustration-37.png");

// Knowledge
const knowledge5 = require("../../assets/images/theme/knowledge-5.png");
const knowledge11 = require("../../assets/images/theme/knowledge-11.png");
const knowledge12 = require("../../assets/images/theme/knowledge-12.png");
const knowledge13 = require("../../assets/images/theme/knowledge-13.png");
const knowledge14 = require("../../assets/images/theme/knowledge-14.png");
const knowledge34 = require("../../assets/images/theme/knowledge-34.png");

// Nature
const nature7 = require("../../assets/images/theme/nature-7.png");
const nature25 = require("../../assets/images/theme/nature-25.png");
const nature26 = require("../../assets/images/theme/nature-26.png");
const nature27 = require("../../assets/images/theme/nature-27.png");
const nature28 = require("../../assets/images/theme/nature-28.png");
const nature40 = require("../../assets/images/theme/nature-40.png");
const nature41 = require("../../assets/images/theme/nature-41.png");

// Photography
const photography15 = require("../../assets/images/theme/photography-15.png");
const photography16 = require("../../assets/images/theme/photography-16.png");
const photography17 = require("../../assets/images/theme/photography-17.png");
const photography18 = require("../../assets/images/theme/photography-18.png");
const photography19 = require("../../assets/images/theme/photography-19.png");
const photography35 = require("../../assets/images/theme/photography-35.png");
const photography36 = require("../../assets/images/theme/photography-36.png");

// Texture
const texture29 = require("../../assets/images/theme/texture-29.png");
const texture30 = require("../../assets/images/theme/texture-30.png");
const texture31 = require("../../assets/images/theme/texture-31.png");
const texture32 = require("../../assets/images/theme/texture-32.png");
const texture42 = require("../../assets/images/theme/texture-42.png");

export const listTheme = [
  {
    id: 1,
    entry_id: null,
    flag: 2,
    name: "Abstract",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        imgLocal: abstract4,
        id: 4,
        group_id: 1,
        name: "Theme 4",
        flag: null,
        is_free: 0,
        font_family: "FjallaOne-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        background: {
          id: 4,
          owner_id: 4,
          type: "theme",
          name: "4.png",
          url: "/assets/images/themes/bg/4.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: abstract9,
        id: 9,
        group_id: 1,
        name: "Theme 9",
        flag: null,
        is_free: 0,
        font_family: "PalatinoLTPro-Medium",
        font_size: 24,
        line_height: 38,
        text_color: "#F0CD96",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":2,"height":2}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 28,
          owner_id: 9,
          type: "theme",
          name: "9.png",
          url: "/assets/images/themes/bg/9.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: abstract10,
        id: 10,
        group_id: 1,
        name: "Theme 10",
        flag: null,
        is_free: 0,
        font_family: "CarterOne",
        font_size: 22,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 29,
          owner_id: 10,
          type: "theme",
          name: "10.png",
          url: "/assets/images/themes/bg/10.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: abstract33,
        id: 33,
        group_id: 1,
        icon: 2,
        name: "Theme 33",
        flag: null,
        is_free: 0,
        font_family: "Montserrat-SemiBold",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        background: {
          id: 52,
          owner_id: 33,
          type: "theme",
          name: "33.png",
          url: "/assets/images/themes/bg/33.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 2,
    entry_id: null,
    flag: 2,
    name: "Knowledge",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        imgLocal: knowledge5,
        id: 5,
        group_id: 2,
        name: "Theme 5",
        flag: null,
        is_free: 0,
        font_family: "Lobster-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        background: {
          id: 5,
          owner_id: 5,
          type: "theme",
          name: "5.png",
          url: "/assets/images/themes/bg/5.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: knowledge11,
        id: 11,
        group_id: 2,
        name: "Theme 11",
        flag: null,
        is_free: 0,
        font_family: "Montserrat-Bold",
        font_size: 20,
        line_height: 28,
        text_color: "#F0CD96",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 30,
          owner_id: 11,
          type: "theme",
          name: "11.png",
          url: "/assets/images/themes/bg/11.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: knowledge12,
        id: 12,
        group_id: 2,
        name: "Theme 12",
        flag: null,
        is_free: 0,
        font_family: "Calistoga-Regular",
        font_size: 22,
        line_height: 34,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 31,
          owner_id: 12,
          type: "theme",
          name: "12.png",
          url: "/assets/images/themes/bg/12.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: knowledge13,
        id: 13,
        group_id: 2,
        name: "Theme 13",
        flag: null,
        is_free: 0,
        font_family: "Hoefler Text Black",
        font_size: 26,
        line_height: 39,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 32,
          owner_id: 13,
          type: "theme",
          name: "13.png",
          url: "/assets/images/themes/bg/13.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: knowledge14,
        id: 14,
        group_id: 2,
        name: "Theme 14",
        flag: null,
        is_free: 0,
        font_family: "Kreon-Regular",
        font_size: 22,
        line_height: 36,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 33,
          owner_id: 14,
          type: "theme",
          name: "14.png",
          url: "/assets/images/themes/bg/14.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        imgLocal: knowledge34,
        id: 34,
        group_id: 2,
        icon: 2,
        name: "Theme 34",
        flag: null,
        is_free: 0,
        font_family: "Montserrat-SemiBold",
        font_size: 24,
        line_height: 38,
        text_color: "#F0CD96",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        background: {
          id: 53,
          owner_id: 34,
          type: "theme",
          name: "34.png",
          url: "/assets/images/themes/bg/34.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 3,
    entry_id: null,
    flag: 2,
    name: "Photography",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        imgLocal: photography15,
        id: 15,
        group_id: 3,
        name: "Theme 15",
        flag: null,
        is_free: 0,
        font_family: "Fondamento-Regular",
        font_size: 22,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        background: {
          id: 34,
          owner_id: 15,
          type: "theme",
          name: "15.png",
          url: "/assets/images/themes/bg/15.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 16,
        group_id: 3,
        name: "Theme 16",
        flag: null,
        is_free: 0,
        font_family: "Calistoga-Regular",
        font_size: 22,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: photography16,
        background: {
          id: 35,
          owner_id: 16,
          type: "theme",
          name: "16.png",
          url: "/assets/images/themes/bg/16.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 17,
        group_id: 3,
        name: "Theme 17",
        flag: null,
        is_free: 0,
        font_family: "Caveat-Bold",
        font_size: 28,
        line_height: 38,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: photography17,
        background: {
          id: 36,
          owner_id: 17,
          type: "theme",
          name: "17.png",
          url: "/assets/images/themes/bg/17.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 18,
        group_id: 3,
        name: "Theme 18",
        flag: null,
        is_free: 0,
        font_family: "LibreBaskerville-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: photography18,
        background: {
          id: 37,
          owner_id: 18,
          type: "theme",
          name: "18.png",
          url: "/assets/images/themes/bg/18.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 19,
        group_id: 3,
        name: "Theme 19",
        flag: null,
        is_free: 0,
        font_family: "Merienda-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: photography19,
        background: {
          id: 38,
          owner_id: 19,
          type: "theme",
          name: "19.png",
          url: "/assets/images/themes/bg/19.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 35,
        group_id: 3,
        icon: 2,
        name: "Theme 35",
        flag: null,
        is_free: 0,
        font_family: "Menlo",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: photography35,
        background: {
          id: 54,
          owner_id: 35,
          type: "theme",
          name: "35.png",
          url: "/assets/images/themes/bg/35.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
      {
        id: 36,
        group_id: 3,
        icon: 2,
        name: "Theme 36",
        flag: null,
        is_free: 0,
        font_family: "Fondamento-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: photography36,
        background: {
          id: 55,
          owner_id: 36,
          type: "theme",
          name: "36.png",
          url: "/assets/images/themes/bg/36.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 4,
    entry_id: null,
    flag: 2,
    name: "Illustration",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        id: 2,
        group_id: 4,
        name: "Theme 2",
        flag: null,
        is_free: 0,
        font_family: "Montserrat-ExtraBold",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        imgLocal: illustration2,
        background: {
          id: 2,
          owner_id: 2,
          type: "theme",
          name: "2.png",
          url: "/assets/images/themes/bg/2.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        id: 3,
        group_id: 4,
        name: "Theme 3",
        flag: null,
        is_free: 0,
        font_family: "Signika-Bold",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        imgLocal: illustration3,
        background: {
          id: 3,
          owner_id: 3,
          type: "theme",
          name: "3.png",
          url: "/assets/images/themes/bg/3.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        id: 6,
        group_id: 4,
        name: "Theme 6",
        flag: null,
        is_free: 0,
        font_family: "Anton-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        imgLocal: illustration6,
        background: {
          id: 6,
          owner_id: 6,
          type: "theme",
          name: "6.png",
          url: "/assets/images/themes/bg/6.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        id: 20,
        group_id: 4,
        name: "Theme 20",
        flag: null,
        is_free: 0,
        font_family: "DeliusSwashCaps-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: illustration20,
        background: {
          id: 39,
          owner_id: 20,
          type: "theme",
          name: "20.png",
          url: "/assets/images/themes/bg/20.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 21,
        group_id: 4,
        name: "Theme 21",
        flag: null,
        is_free: 0,
        font_family: "Rowdies-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: illustration21,
        background: {
          id: 40,
          owner_id: 21,
          type: "theme",
          name: "21.png",
          url: "/assets/images/themes/bg/21.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 37,
        group_id: 4,
        icon: 2,
        name: "Theme 37",
        flag: null,
        is_free: 0,
        font_family: "DeliusSwashCaps-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: illustration37,
        background: {
          id: 56,
          owner_id: 37,
          type: "theme",
          name: "37.png",
          url: "/assets/images/themes/bg/37.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 5,
    entry_id: null,
    flag: 2,
    name: "Cityscape",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        id: 8,
        group_id: 5,
        name: "Theme 8",
        flag: null,
        is_free: 0,
        font_family: "ChakraPetch-Medium",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        imgLocal: cityScape8,
        background: {
          id: 8,
          owner_id: 8,
          type: "theme",
          name: "8.png",
          url: "/assets/images/themes/bg/8.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        id: 22,
        group_id: 5,
        name: "Theme 22",
        flag: null,
        is_free: 0,
        font_family: "PatuaOne-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#F0CD96",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: cityScape22,
        background: {
          id: 41,
          owner_id: 22,
          type: "theme",
          name: "22.png",
          url: "/assets/images/themes/bg/22.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 23,
        group_id: 5,
        name: "Theme 23",
        flag: null,
        is_free: 0,
        font_family: "IbarraRealNova-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: cityScape23,
        background: {
          id: 42,
          owner_id: 23,
          type: "theme",
          name: "23.png",
          url: "/assets/images/themes/bg/23.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 24,
        group_id: 5,
        name: "Theme 24",
        flag: null,
        is_free: 0,
        font_family: "RussoOne-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: cityScape24,
        background: {
          id: 43,
          owner_id: 24,
          type: "theme",
          name: "24.png",
          url: "/assets/images/themes/bg/24.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 38,
        group_id: 5,
        icon: 2,
        name: "Theme 38",
        flag: null,
        is_free: 0,
        font_family: "IbarraRealNova-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: cityScape38,
        background: {
          id: 57,
          owner_id: 38,
          type: "theme",
          name: "38.png",
          url: "/assets/images/themes/bg/38.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
      {
        id: 39,
        group_id: 5,
        icon: 2,
        name: "Theme 39",
        flag: null,
        is_free: 0,
        font_family: "PatuaOne-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: cityScape39,
        background: {
          id: 58,
          owner_id: 39,
          type: "theme",
          name: "39.png",
          url: "/assets/images/themes/bg/39.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 6,
    entry_id: null,
    flag: 2,
    name: "Nature",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        id: 7,
        group_id: 6,
        name: "Theme 7",
        flag: null,
        is_free: 0,
        font_family: "FjallaOne-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFD600",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:36.000000Z",
        updated_at: null,
        imgLocal: nature7,
        background: {
          id: 7,
          owner_id: 7,
          type: "theme",
          name: "7.png",
          url: "/assets/images/themes/bg/7.png",
          created_at: "2023-06-13T08:15:36.000000Z",
          updated_at: null,
        },
      },
      {
        id: 25,
        group_id: 6,
        name: "Theme 25",
        flag: null,
        is_free: 0,
        font_family: "PalatinoLTPro-Medium",
        font_size: 24,
        line_height: 38,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: nature25,
        background: {
          id: 44,
          owner_id: 25,
          type: "theme",
          name: "25.png",
          url: "/assets/images/themes/bg/25.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 26,
        group_id: 6,
        name: "Theme 26",
        flag: null,
        is_free: 0,
        font_family: "FrankRuhlLibre-Medium",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: nature26,
        background: {
          id: 45,
          owner_id: 26,
          type: "theme",
          name: "26.png",
          url: "/assets/images/themes/bg/26.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 27,
        group_id: 6,
        name: "Theme 27",
        flag: null,
        is_free: 0,
        font_family: "Tinos-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: nature27,
        background: {
          id: 46,
          owner_id: 27,
          type: "theme",
          name: "27.png",
          url: "/assets/images/themes/bg/27.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 28,
        group_id: 6,
        name: "Theme 28",
        flag: null,
        is_free: 0,
        font_family: "IM FELL DW Pica",
        font_size: 24,
        line_height: 38,
        text_color: "#000000",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: nature28,
        background: {
          id: 47,
          owner_id: 28,
          type: "theme",
          name: "28.png",
          url: "/assets/images/themes/bg/28.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 40,
        group_id: 6,
        icon: 2,
        name: "Theme 40",
        flag: null,
        is_free: 0,
        font_family: "Fredoka SemiBold",
        font_size: 24,
        line_height: 38,
        text_color: "#FFD600",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: nature40,
        background: {
          id: 59,
          owner_id: 40,
          type: "theme",
          name: "40.png",
          url: "/assets/images/themes/bg/40.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
      {
        id: 41,
        group_id: 6,
        icon: 2,
        name: "Theme 41",
        flag: null,
        is_free: 0,
        font_family: "Optima",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: nature41,
        background: {
          id: 60,
          owner_id: 41,
          type: "theme",
          name: "41.png",
          url: "/assets/images/themes/bg/41.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
  {
    id: 7,
    entry_id: null,
    flag: 2,
    name: "Texture",
    status: 2,
    created_at: "2023-06-13T08:15:36.000000Z",
    updated_at: null,
    themes: [
      {
        id: 29,
        group_id: 7,
        name: "Theme 29",
        flag: null,
        is_free: 0,
        font_family: "Prata-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#FFC700",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: texture29,
        background: {
          id: 48,
          owner_id: 29,
          type: "theme",
          name: "29.png",
          url: "/assets/images/themes/bg/29.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 30,
        group_id: 7,
        name: "Theme 30",
        flag: null,
        is_free: 0,
        font_family: "Fondamento-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: texture30,
        background: {
          id: 49,
          owner_id: 30,
          type: "theme",
          name: "30.png",
          url: "/assets/images/themes/bg/30.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 31,
        group_id: 7,
        name: "Theme 31",
        flag: null,
        is_free: 0,
        font_family: "Calistoga-Regular",
        font_size: 24,
        line_height: 38,
        text_color: "#FFC76D",
        text_shadow: null,
        text_shadow_offset: null,
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: texture31,
        background: {
          id: 50,
          owner_id: 31,
          type: "theme",
          name: "31.png",
          url: "/assets/images/themes/bg/31.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 32,
        group_id: 7,
        name: "Theme 32",
        flag: null,
        is_free: 0,
        font_family: "LibreBaskerville-Bold",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-06-13T08:15:37.000000Z",
        updated_at: null,
        imgLocal: texture32,
        background: {
          id: 51,
          owner_id: 32,
          type: "theme",
          name: "32.png",
          url: "/assets/images/themes/bg/32.png",
          created_at: "2023-06-13T08:15:37.000000Z",
          updated_at: null,
        },
      },
      {
        id: 42,
        group_id: 7,
        icon: 2,
        name: "Theme 42",
        flag: null,
        is_free: 0,
        font_family: "Koulen-Regular",
        font_size: 24,
        line_height: 34,
        text_color: "#FFFFFF",
        text_shadow: "rgba(0, 0, 0, 0.75)",
        text_shadow_offset: '{"width":1,"height":1}',
        background_color: null,
        bg_image_color: null,
        status: 2,
        created_at: "2023-08-10T04:09:12.000000Z",
        updated_at: null,
        imgLocal: texture42,
        background: {
          id: 61,
          owner_id: 42,
          type: "theme",
          name: "42.png",
          url: "/assets/images/themes/bg/42.png",
          created_at: "2023-08-10T04:09:12.000000Z",
          updated_at: null,
        },
      },
    ],
  },
];

export const getArrThemes = () => {
  const mergedThemes = [];

  listTheme.forEach((item) => {
    item.themes.forEach((theme) => {
      mergedThemes.push(theme);
    });
  });

  return mergedThemes;
};
